/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_migrsoft_nbk_LoaderMgr */

#ifndef _Included_com_migrsoft_nbk_LoaderMgr
#define _Included_com_migrsoft_nbk_LoaderMgr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_migrsoft_nbk_LoaderMgr
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_migrsoft_nbk_LoaderMgr_register
  (JNIEnv *, jobject);

/*
 * Class:     com_migrsoft_nbk_LoaderMgr
 * Method:    nbkLoaderResponse
 * Signature: (IIILjava/lang/String;III[B)V
 */
JNIEXPORT void JNICALL Java_com_migrsoft_nbk_LoaderMgr_nbkLoaderResponse
  (JNIEnv *, jobject, jint, jint, jint, jstring, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
