/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_migrsoft_nbk_ImageMgr_Nimage */

#ifndef _Included_com_migrsoft_nbk_ImageMgr_Nimage
#define _Included_com_migrsoft_nbk_ImageMgr_Nimage
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
