/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_migrsoft_nbk_Graphic_FontInfo */

#ifndef _Included_com_migrsoft_nbk_Graphic_FontInfo
#define _Included_com_migrsoft_nbk_Graphic_FontInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
