/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_migrsoft_nbk_Graphic */

#ifndef _Included_com_migrsoft_nbk_Graphic
#define _Included_com_migrsoft_nbk_Graphic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_migrsoft_nbk_Graphic
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_migrsoft_nbk_Graphic_register
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
