/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_migrsoft_nbk_LoaderMgr_HttpGet */

#ifndef _Included_com_migrsoft_nbk_LoaderMgr_HttpGet
#define _Included_com_migrsoft_nbk_LoaderMgr_HttpGet
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
