/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_migrsoft_nbk_LoaderMgr_LoadData */

#ifndef _Included_com_migrsoft_nbk_LoaderMgr_LoadData
#define _Included_com_migrsoft_nbk_LoaderMgr_LoadData
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
