/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_migrsoft_nbk_TimerMgr_TimerJob */

#ifndef _Included_com_migrsoft_nbk_TimerMgr_TimerJob
#define _Included_com_migrsoft_nbk_TimerMgr_TimerJob
#ifdef __cplusplus
extern "C" {
#endif
#undef com_migrsoft_nbk_TimerMgr_TimerJob_VIRGIN
#define com_migrsoft_nbk_TimerMgr_TimerJob_VIRGIN 0L
#undef com_migrsoft_nbk_TimerMgr_TimerJob_SCHEDULED
#define com_migrsoft_nbk_TimerMgr_TimerJob_SCHEDULED 1L
#undef com_migrsoft_nbk_TimerMgr_TimerJob_EXECUTED
#define com_migrsoft_nbk_TimerMgr_TimerJob_EXECUTED 2L
#undef com_migrsoft_nbk_TimerMgr_TimerJob_CANCELLED
#define com_migrsoft_nbk_TimerMgr_TimerJob_CANCELLED 3L
#ifdef __cplusplus
}
#endif
#endif
