/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_migrsoft_nbk_ImageMgr */

#ifndef _Included_com_migrsoft_nbk_ImageMgr
#define _Included_com_migrsoft_nbk_ImageMgr
#ifdef __cplusplus
extern "C" {
#endif
#undef com_migrsoft_nbk_ImageMgr_MAX_IMAGES
#define com_migrsoft_nbk_ImageMgr_MAX_IMAGES 200L
/*
 * Class:     com_migrsoft_nbk_ImageMgr
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_migrsoft_nbk_ImageMgr_register
  (JNIEnv *, jobject);

/*
 * Class:     com_migrsoft_nbk_ImageMgr
 * Method:    nbkImageDecodeOver
 * Signature: (IZII)V
 */
JNIEXPORT void JNICALL Java_com_migrsoft_nbk_ImageMgr_nbkImageDecodeOver
  (JNIEnv *, jobject, jint, jboolean, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
