/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_migrsoft_nbk_TimerMgr */

#ifndef _Included_com_migrsoft_nbk_TimerMgr
#define _Included_com_migrsoft_nbk_TimerMgr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_migrsoft_nbk_TimerMgr
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_migrsoft_nbk_TimerMgr_register
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
